notes/aks/urls.py
from django.urls import path
from aks.views import note_create, note_list, note_detail, note_delete

app_name = 'aks'

urlpatterns = [
    path("note_list", note_list, name='note_list'),
    path('note_detail/<int:pk>/', note_detail, name='note_detail'),
    path("note_create/", note_create, name='note_create'),
    path('note_delete/<int:pk>/delete/', note_delete, name='note_delete'),
]

notes/main/urls.py
from django.urls import path
from main.views import main

app_name = 'main'

urlpatterns = [
    path("", main, name='main'),
]

notes/notes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('aks/', include('aks.urls'))
]

notes/users/urls.py
from django.urls import path
from users.views import login, register, profile, exit

app_name = 'users'

urlpatterns = [
    path("login/", login, name='login'),
    path("register/", register, name='register'),
    path('profile/', profile, name="profile"),
    path('exit/', exit, name="exit"),
]

notes/aks/models.py
from django.db import models
from django.conf import settings

class Note(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="Note")
    title = models.CharField(max_length=200)
    content = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title

notes/main/models.py
from django.db import models

notes/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='users_imeges', null=True, blank=True)
    

notes/aks/forms.py
from django import forms
from .models import Note

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'content']

notes/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User

class UserLoginFrom(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "class": "form-control py-4", "placeholder": "Імя користувача"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "form-control py-4", "placeholder": "Пароль"}))
    class Meta:
        model = User
        fields = ('username', 'password')

class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        "class": "form-control py-4", "placeholder": "Імя"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        "class": "form-control py-4", "placeholder": "Прізвище"}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        "class": "form-control py-4", "placeholder": "Імя користувача"}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        "class": "form-control py-4", "placeholder": "емеіл"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "form-control py-4", "placeholder": "пароль"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "form-control py-4", "placeholder": "Підтвердите пароль"}))
    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "email", "password1", "password2")

class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control py-4"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control py-4"}))
    image = forms.ImageField(widget=forms.FileInput(attrs={"class": "form-control py-4"}), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control py-4", "readonly": True}))
    email = forms.CharField(widget=forms.EmailInput(attrs={"class": "form-control py-4", "readonly": True}))

    class Meta:
            model = User
            fields = ("first_name", "last_name", "username", "email","image") 

notes/aks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Note
from .forms import NoteForm

@login_required
def note_list(request):

    if request.method == 'POST' and "form_izi" in request.POST:
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.user = request.user
            note.save()
            return redirect('aks:note_list')
    else:
        form = NoteForm()

    if request.method == 'POST' and 'delete_note' in request.POST:
        print("работає")
        note_id = request.POST.get('delete_note')
        note = get_object_or_404(Note, id=note_id, user=request.user)
        note.delete()
        return redirect('aks:note_list')

    notes = Note.objects.filter(user=request.user)
    return render(request, 'notes/note_list.html', {'form': form, 'notes': notes})

@login_required
def note_detail(request, pk):
    note = get_object_or_404(Note, pk=pk, user=request.user)
    return render(request, 'notes/note_detail.html', {'note': note})
    

@login_required
def note_create(request):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.user = request.user
            note.save()
            return redirect('aks:note_list')
    else:
        form = NoteForm()
    return render(request, 'notes/note_form.html', {'form': form})

def note_update(request, pk):
    note = get_object_or_404(Note, pk=pk, user=request.user)
    if request.method == 'POST':
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            form.save()
            return redirect('note_list')
    else:
        form = NoteForm(instance=note)
    return render(request, 'notes/note_form.html', {'form': form})

@login_required
def note_delete(request, pk):
    note = get_object_or_404(Note, pk=pk, user=request.user)
    if request.method == 'POST':
        note.delete()
        return redirect('aks:note_list')
    return render(request, 'notes/note_confirm_delete.html', {'note': note})

notes/main/views.py
from django.shortcuts import render

def main(request):
    return render(request, 'main/main.html')

notes/users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required


from users.forms import UserLoginFrom, UserRegistrationForm, UserProfileForm


def login(request):
    if request.method == "POST":
        form = UserLoginFrom(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse("main:main"))
    else:
        form  = UserLoginFrom()
    context = {'form': form}
    return render(request, 'users/login.html', context)

def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Акаунт успішно созданий")
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form  = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/register.html', context) 

@login_required
def profile(request):
    if request.method == "POST":
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
        else:
            print(form.errors)
    else:
        form = UserProfileForm(instance=request.user)


    return render(request, "users/profile.html")  

def exit(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:main'))

notes/aks/templates/notes/note_confirm_delete.html
{% extends 'main/xx.html' %}

{% block title %}Деталі нотатки{% endblock %}

{% block sale %}
<main>
<h1>Ви впевнені, що хочете видалити "{{ note.title }}"?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Так</button>
        <a href="{% url 'aks:note_list' %}">Скасувати</a>
    </form>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }} 
        <button type="submit">Зберегти</button>
    </form>
</main>
{% endblock %}

notes/aks/templates/notes/note_detail.html
{% extends 'main/xx.html' %}

{% block title %}Деталі нотатки{% endblock %}

{% block sale %}
<main>
    <h1>{{ note.title }}</h1>
    <p>{{ note.content }}</p>
    <hr>
    <p>Створено: {{ note.created_at|date:"d-m-Y H:i" }}</p>
    <p>Оновлено: {{ note.updated_at|date:"d-m-Y H:i" }}</p>
    
    <a href="{% url 'aks:note_list' %}" class="button">Назад до списку</a>
</main>
{% endblock %}

notes/aks/templates/notes/note_form.html
{% extends 'main/xx.html' %}

{% block title %}sexshop{% endblock %}

{% load static %}

<link rel="stylesheet" href="{% static  'css/auth.css' %}">

{% block sale %}
<main>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }} 
        <button type="submit">Зберегти</button>
    </form>
</main>
{% endblock %}

notes/aks/templates/notes/note_list.html
{% extends 'main/xx.html' %}

{% block title %}sexshop{% endblock %}

{% load static %}

<link rel="stylesheet" href="{% static  'css/auth.css' %}">

{% block sale %}
<main>
    <h1>Ваші нотатки</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }} 
        <button type="submit" name="form_izi">Зберегти</button>
    </form>
<ul>
    {% for note in notes %}
        <li>
            {% if note.pk %}
                <a href="{% url 'aks:note_detail' note.pk %}">{{ note.title }}</a>
                <form method="post" action="{% url 'aks:note_list' %}" style="display:inline;">
                    {% csrf_token %}
                    <input type="hidden" name="delete_note" value="{{ note.id }}">
                    <button type="submit" style="color:red;">Видалити</button>
                </form>
            {% else %}
                <span>Некоректна нотатка</span>
            {% endif %}
        </li>
    {% endfor %}
</ul>
</main>
{% endblock %}

notes/main/templates/main/main.html
{% load static %}
<!DOCTYPE html>
<html lang="ua">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>main</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static  'css/main.css' %}">
    
</head>
<body>
    {% if user.is_authenticated %}
        <a href="{% url 'users:profile'%}"> Профіль </a>
    {% else %}
        <a href="{% url 'users:login'%}"> Войти </a>
    {% endif %}
    <a href="{% url 'aks:note_list'%}">лист</a>
    <a href="{% url 'aks:note_create'%}">создание листа</a>
</body>

notes/main/templates/main/xx.html
{% load static %}
<!DOCTYPE html>
<html lang="ua">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static  'css/main.css' %}">
    
</head>
<body>
    <header>
        <a id="ava" href="{% url 'main:main' %}">sexshop</a>
        
        <div id="hightshapka">
            {% if user.is_authenticated %}
                <a href="{% url 'users:profile'%}"> Профіль </a>
            {% else %}
                <a href="{% url 'users:login'%}"> Войти </a>
            {% endif %}
        </div>
    </header>
<div class="f">
    {% block sale %}
    {% endblock %}
</div>
    <footer class="nuz">
        <div id="top">
            <div class="top">Топ покупців:</div>
            <div class="top">1. Андрій Заводський</div>
            <div class="top">2. Важке прізвище Назар</div>
        </div>
        <div id="contact">
            <div class="contact">Контакти</div>
            <div class="contact">Номер: none</div>
            <div class="contact">Тлеграм: none</div>
            <div class="contact">Інстаграм: none</div>
        </div>
    </footer>
</body>
</html>

notes/users/templates/users/base.html
{% load  static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Store - Регистрация</title>
    <link href="{% static  'css/auth.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        {% block content%}
        
        {% endblock%}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js\auth-admin.js'%}"></script>
</body>
</html>

notes/users/templates/users/login.html
{% extends 'users/base.html' %}
{% block content %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                {% if messages or form.non_field_errors%}
                    <div class="alert 
                        {% if messages%}
                            alert-success
                        {%else%}
                            alert-warning
                        {%endif%}
                    alert-dismissible fade show" role="alert"
                        style="margin-top: 50px;">
                        {% if messages %}
                            {%for message in messages%}
                                {{ message }}
                            {% endfor %}
                        {%else%}
                            {{ form.non_field_errors}}
                        {% endif %}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {%endif%}
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                    </div>
                    <div class="card-body">
                        <form action='{% url "users:login" %}' method='post'>
                            {% csrf_token %}

                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.username.id_for_label }}">Імя користувача</label>
                                {{ form.username }}
                            </div>
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.password.id_for_label}}">Пароль</label>
                                {{ form.password }}
                            </div>

                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                <a class="small" href="#">Забыли пароль?</a>
                                <input class="btn btn-primary" type="submit" value="Авторизоваться">
                            </div>
                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                <a href="#">
                                    <i class="fab fa-google fa-2x" style="color: #d9503e;"></i>
                                </a>
                                <a href="#">
                                    <i class="fab fa-vk fa-2x" style="color: #4a658b;"></i>
                                </a>
                                <a href="#">
                                    <i class="fab fa-github fa-2x" style="color: #303030;"></i>
                                </a>
                                <a href="#">
                                    <i class="fab fa-facebook fa-2x" style="color: #405794;"></i>
                                </a>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small"><a href="{% url 'users:register'%}">Нужен аккаунт? Зарегистрируйся!</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

notes/users/templates/users/profile.html
{% extends 'main/xx.html' %}

{% block title %}sexshop{% endblock %}

{% load static %}

<link rel="stylesheet" href="{% static  'css/auth.css' %}">

{% block sale %}
<main>
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <h4 class="mt-3 mb-3">Профиль</h4>
                <div class="col-lg-12 text-center">
                    <img width="100" height="100"
                         src="{% static "img\avatar-is-hooded-indicated-by-question-mark-anonymous-unauthorized-user-isolated-vector_619989-1333.avif"%}"
                         class="img-thumbnail">
                </div>
                <form action="{% url "users:profile" %}" method="post", enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label}}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{form.last_name.id_for_label}}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Воно не працює, бюджету не вистачило</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{form.username.id_for_label}}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{form.email.id_for_label}}">Адрес электронной
                                почты</label>
                            {{ form.email}}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            <a href="{%url 'users:exit'%}">Вийти</a>
                        </div>
                    </div>
                </form>
            </div>
            
        </div>
    </div>
</main>
{% endblock %}

notes/users/templates/users/register.html
{% extends 'users/base.html' %}
{% block content %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                {% if form.errors%}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert"
                        style="margin-top: 50px;">
                        {{ form.errors }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {%endif%}
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'users:register' %}" method="post">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{form.first_name.id_for_label}}">Имя</label>
                                        {{ form.first_name }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{form.last_name.id_for_label}}">Фамилия</label>
                                        {{ form.last_name}}
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-6">
                                    <label class="small mb-1" for="{{form.username.id_for_label}}">Имя пользователя</label>
                                    {{ form.username}}
                                </div>
                                <div class="col-md-6">
                                    <label class="small mb-1" for="{{form.email.id_for_label}}">Адрес электронной
                                        почты</label>
                                        {{ form.email}}
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{form.password1.id_for_label}}">Пароль</label>
                                        {{ form.password1}}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{form.password2.id_for_label}}">Подтверждение
                                            пароля</label>
                                        {{ form.password2}}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group mt-4 mb-0">
                                <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small"><a href="{% url 'users:login'%}">Уже есть аккаунт? Авторизоваться</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}